server:
    shutdown: graceful
---
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: TRACE
---
management:
    endpoints:
        jmx:
            exposure:
                include: "health,info"
        web:
            exposure:
                include: "*"
                exclude: "env,beans"
---
spring:
    lifecycle:
        timeout-per-shutdown-phase: 1m

    jackson:
        default-property-inclusion: non_null
        serialization:
            write-dates-with-zone-id: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/streaming-service?prepareThreshold=0}
        username: ${DB_USERNAME:streaming-service}
        password: ${DB_USERNAME:streaming-service}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 1
            leak-detection-threshold: 30000
            connection-timeout: 5000
            connection-test-query: SELECT 1
