server:
    shutdown: graceful
---
logging:
    level:
        org:
            springframework:
                jdbc:
                    core: info
---
management:
    endpoints:
        jmx:
            exposure:
                include: "health,info"
        web:
            exposure:
                include: "*"
                exclude: "env,beans"
---
spring:
    lifecycle:
        timeout-per-shutdown-phase: 1m

    jackson:
        default-property-inclusion: non_null
        serialization:
            write-dates-with-zone-id: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL:jdbc:postgresql://localhost:5432/streaming-service?prepareThreshold=0}
        username: ${DB_USERNAME:streaming-service}
        password: ${DB_USERNAME:streaming-service}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 1
            leak-detection-threshold: 30000
            connection-timeout: 5000
            connection-test-query: SELECT 1

    cloud:
        aws:
            endpoint: http://localhost:4566
            region:
                static: us-east-1
            credentials:
                access-key: noop
                secret-key: noop
            s3:
                path-style-access-enabled: true

    task:
        execution:
            pool:
                core-size: 5  # Configure the core pool size
                max-size: 10  # Configure the maximum pool size

    servlet:
        multipart:
            max-request-size: 1GB
            max-file-size: 1GB
---
streaming-service:
    topics:
        arns:
            episode-uploaded: arn:aws:sns:us-east-1:000000000000:EPISODE_UPLOADED_NOTIFICATION
    buckets:
        names:
            videos: videos-bucket

---
hash:
    secret: SECRET_KEY
---
vod:
    ip:
    base-url: http://${ip:localhost}/hls/vod/
    suffix: .urlset/master.m3u8