package br.com.rodrigogurgel.streamingservice.domain

enum class SubtitleEnum(val `iso639-2`: String, val languageName: String) {
    AAR("aar", "Afar"),
    ABK("abk", "Abkhazian"),
    ACE("ace", "Achinese"),
    ACH("ach", "Acoli"),
    ADA("ada", "Adangme"),
    ADY("ady", "Adyghe; Adygei"),
    AFA("afa", "Afro-Asiatic languages"),
    AFH("afh", "Afrihili"),
    AFR("afr", "Afrikaans"),
    AIN("ain", "Ainu"),
    AKA("aka", "Akan"),
    AKK("akk", "Akkadian"),
    ALE("ale", "Aleut"),
    ALG("alg", "Algonquian languages"),
    ALT("alt", "Southern Altai"),
    AMH("amh", "Amharic"),
    ANG("ang", "English, Old (ca.450–1100)"),
    ANP("anp", "Angika"),
    APA("apa", "Apache languages"),
    ARA("ara", "Arabic"),
    ARC("arc", "Official Aramaic (700–300 BCE); Imperial Aramaic (700–300 BCE)"),
    ARG("arg", "Aragonese"),
    ARN("arn", "Mapudungun; Mapuche"),
    ARP("arp", "Arapaho"),
    ART("art", "Artificial languages"),
    ARW("arw", "Arawak"),
    ASM("asm", "Assamese"),
    AST("ast", "Asturian; Bable; Leonese; Asturleonese"),
    ATH("ath", "Athapascan languages"),
    AUS("aus", "Australian languages"),
    AVA("ava", "Avaric"),
    AVE("ave", "Avestan"),
    AWA("awa", "Awadhi"),
    AYM("aym", "Aymara"),
    AZE("aze", "Azerbaijani"),
    BAD("bad", "Banda languages"),
    BAI("bai", "Bamileke languages"),
    BAK("bak", "Bashkir"),
    BAL("bal", "Baluchi"),
    BAM("bam", "Bambara"),
    BAN("ban", "Balinese"),
    BAS("bas", "Basa"),
    BAT("bat", "Baltic languages"),
    BEJ("bej", "Beja; Bedawiyet"),
    BEL("bel", "Belarusian"),
    BEM("bem", "Bemba"),
    BEN("ben", "Bengali"),
    BER("ber", "Berber languages"),
    BHO("bho", "Bhojpuri"),
    BIH("bih", "Bihari languages"),
    BIK("bik", "Bikol"),
    BIN("bin", "Bini; Edo"),
    BIS("bis", "Bislama"),
    BLA("bla", "Siksika"),
    BNT("bnt", "Bantu languages"),
    BOD("bod", "Tibetan"),
    TIB("tib", "Tibetan"),
    BOS("bos", "Bosnian"),
    BRA("bra", "Braj"),
    BRE("bre", "Breton"),
    BTK("btk", "Batak languages"),
    BUA("bua", "Buriat"),
    BUG("bug", "Buginese"),
    BUL("bul", "Bulgarian"),
    BYN("byn", "Blin; Bilin"),
    CAD("cad", "Caddo"),
    CAI("cai", "Central American Indian languages"),
    CAR("car", "Galibi Carib"),
    CAT("cat", "Catalan; Valencian"),
    CAU("cau", "Caucasian languages"),
    CEB("ceb", "Cebuano"),
    CEL("cel", "Celtic languages"),
    CES("ces", "Czech"),
    CZE("cze", "Czech"),
    CHA("cha", "Chamorro"),
    CHB("chb", "Chibcha"),
    CHE("che", "Chechen"),
    CHG("chg", "Chagatai"),
    CHK("chk", "Chuukese"),
    CHM("chm", "Mari"),
    CHN("chn", "Chinook jargon"),
    CHO("cho", "Choctaw"),
    CHP("chp", "Chipewyan; Dene Suline"),
    CHR("chr", "Cherokee"),
    CHU("chu", "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
    CHV("chv", "Chuvash"),
    CHY("chy", "Cheyenne"),
    CMC("cmc", "Chamic languages"),
    CNR("cnr", "Montenegrin"),
    COP("cop", "Coptic"),
    COR("cor", "Cornish"),
    COS("cos", "Corsican"),
    CPE("cpe", "Creoles and pidgins, English based"),
    CPF("cpf", "Creoles and pidgins, French-based"),
    CPP("cpp", "Creoles and pidgins, Portuguese-based"),
    CRE("cre", "Cree"),
    CRH("crh", "Crimean Tatar; Crimean Turkish"),
    CRP("crp", "Creoles and pidgins"),
    CSB("csb", "Kashubian"),
    CUS("cus", "Cushitic languages"),
    CYM("cym", "Welsh"),
    WEL("wel", "Welsh"),
    DAK("dak", "Dakota"),
    DAN("dan", "Danish"),
    DAR("dar", "Dargwa"),
    DAY("day", "Land Dayak languages"),
    DEL("del", "Delaware"),
    DEN("den", "Slave (Athapascan)"),
    DEU("deu", "German"),
    GER("ger", "German"),
    DGR("dgr", "Dogrib"),
    DIN("din", "Dinka"),
    DIV("div", "Divehi; Dhivehi; Maldivian"),
    DOI("doi", "Dogri"),
    DRA("dra", "Dravidian languages"),
    DSB("dsb", "Lower Sorbian"),
    DUA("dua", "Duala"),
    DUM("dum", "Dutch, Middle (ca. 1050–1350)"),
    DYU("dyu", "Dyula"),
    DZO("dzo", "Dzongkha"),
    EFI("efi", "Efik"),
    EGY("egy", "Egyptian (Ancient)"),
    EKA("eka", "Ekajuk"),
    ELL("ell", "Greek, Modern (1453–)"),
    GRE("gre", "Greek, Modern (1453–)"),
    ELX("elx", "Elamite"),
    ENG("eng", "English"),
    ENM("enm", "English, Middle (1100–1500)"),
    EPO("epo", "Esperanto"),
    EST("est", "Estonian"),
    EUS("eus", "Basque"),
    BAQ("baq", "Basque"),
    EWE("ewe", "Ewe"),
    EWO("ewo", "Ewondo"),
    FAN("fan", "Fang"),
    FAO("fao", "Faroese"),
    FAS("fas", "Persian"),
    PER("per", "Persian"),
    FAT("fat", "Fanti"),
    FIJ("fij", "Fijian"),
    FIL("fil", "Filipino; Pilipino"),
    FIN("fin", "Finnish"),
    FIU("fiu", "Finno-Ugrian languages"),
    FON("fon", "Fon"),
    FRA("fra", "French"),
    FRE("fre", "French"),
    FRM("frm", "French, Middle (ca. 1400–1600)"),
    FRO("fro", "French, Old (842–ca. 1400)"),
    FRR("frr", "Northern Frisian"),
    FRS("frs", "East Frisian Low Saxon"),
    FRY("fry", "Western Frisian"),
    FUL("ful", "Fulah"),
    FUR("fur", "Friulian"),
    GAA("gaa", "Ga"),
    GAY("gay", "Gayo"),
    GBA("gba", "Gbaya"),
    GEM("gem", "Germanic languages"),
    GEZ("gez", "Geez"),
    GIL("gil", "Gilbertese"),
    GLA("gla", "Gaelic; Scottish Gaelic"),
    GLE("gle", "Irish"),
    GLG("glg", "Galician"),
    GLV("glv", "Manx"),
    GMH("gmh", "German, Middle High (ca. 1050–1500)"),
    GOH("goh", "German, Old High (ca. 750–1050)"),
    GON("gon", "Gondi"),
    GOR("gor", "Gorontalo"),
    GOT("got", "Gothic"),
    GRB("grb", "Grebo"),
    GRC("grc", "Greek, Ancient (to 1453)"),
    GRN("grn", "Guarani"),
    GSW("gsw", "Swiss German; Alemannic; Alsatian"),
    GUJ("guj", "Gujarati"),
    GWI("gwi", "Gwich'in"),
    HAI("hai", "Haida"),
    HAT("hat", "Haitian; Haitian Creole"),
    HAU("hau", "Hausa"),
    HAW("haw", "Hawaiian"),
    HEB("heb", "Hebrew"),
    HER("her", "Herero"),
    HIL("hil", "Hiligaynon"),
    HIM("him", "Himachali languages; Pahari languages"),
    HIN("hin", "Hindi"),
    HIT("hit", "Hittite"),
    HMN("hmn", "Hmong; Mong"),
    HMO("hmo", "Hiri Motu"),
    HRV("hrv", "Croatian"),
    HSB("hsb", "Upper Sorbian"),
    HUN("hun", "Hungarian"),
    HUP("hup", "Hupa"),
    HYE("hye", "Armenian"),
    ARM("arm", "Armenian"),
    IBA("iba", "Iban"),
    IBO("ibo", "Igbo"),
    IDO("ido", "Ido"),
    III("iii", "Sichuan Yi; Nuosu"),
    IJO("ijo", "Ijo languages"),
    IKU("iku", "Inuktitut"),
    ILE("ile", "Interlingue; Occidental"),
    ILO("ilo", "Iloko"),
    INA("ina", "Interlingua (International Auxiliary Language Association)"),
    INC("inc", "Indo-Aryan languages"),
    IND("ind", "Indonesian"),
    INE("ine", "Indo-European languages"),
    INH("inh", "Ingush"),
    IPK("ipk", "Inupiaq"),
    IRA("ira", "Iranian languages"),
    IRO("iro", "Iroquoian languages"),
    ISL("isl", "Icelandic"),
    ICE("ice", "Icelandic"),
    ITA("ita", "Italian"),
    JAV("jav", "Javanese"),
    JBO("jbo", "Lojban"),
    JPN("jpn", "Japanese"),
    JPR("jpr", "Judeo-Persian"),
    JRB("jrb", "Judeo-Arabic"),
    KAA("kaa", "Kara-Kalpak"),
    KAB("kab", "Kabyle"),
    KAC("kac", "Kachin; Jingpho"),
    KAL("kal", "Kalaallisut; Greenlandic"),
    KAM("kam", "Kamba"),
    KAN("kan", "Kannada"),
    KAR("kar", "Karen languages"),
    KAS("kas", "Kashmiri"),
    KAT("kat", "Georgian"),
    GEO("geo", "Georgian"),
    KAU("kau", "Kanuri"),
    KAW("kaw", "Kawi"),
    KAZ("kaz", "Kazakh"),
    KBD("kbd", "Kabardian"),
    KHA("kha", "Khasi"),
    KHI("khi", "Khoisan languages"),
    KHM("khm", "Central Khmer"),
    KHO("kho", "Khotanese; Sakan"),
    KIK("kik", "Kikuyu; Gikuyu"),
    KIN("kin", "Kinyarwanda"),
    KIR("kir", "Kirghiz; Kyrgyz"),
    KMB("kmb", "Kimbundu"),
    KOK("kok", "Konkani"),
    KOM("kom", "Komi"),
    KON("kon", "Kongo"),
    KOR("kor", "Korean"),
    KOS("kos", "Kosraean"),
    KPE("kpe", "Kpelle"),
    KRC("krc", "Karachay-Balkar"),
    KRL("krl", "Karelian"),
    KRO("kro", "Kru languages"),
    KRU("kru", "Kurukh"),
    KUA("kua", "Kuanyama; Kwanyama"),
    KUM("kum", "Kumyk"),
    KUR("kur", "Kurdish"),
    KUT("kut", "Kutenai"),
    LAD("lad", "Ladino"),
    LAH("lah", "Lahnda"),
    LAM("lam", "Lamba"),
    LAO("lao", "Lao"),
    LAT("lat", "Latin"),
    LAV("lav", "Latvian"),
    LEZ("lez", "Lezghian"),
    LIM("lim", "Limburgan; Limburger; Limburgish"),
    LIN("lin", "Lingala"),
    LIT("lit", "Lithuanian"),
    LOL("lol", "Mongo"),
    LOZ("loz", "Lozi"),
    LTZ("ltz", "Luxembourgish; Letzeburgesch"),
    LUA("lua", "Luba-Lulua"),
    LUB("lub", "Luba-Katanga"),
    LUG("lug", "Ganda"),
    LUI("lui", "Luiseno"),
    LUN("lun", "Lunda"),
    LUO("luo", "Luo (Kenya and Tanzania)"),
    LUS("lus", "Lushai"),
    MAD("mad", "Madurese"),
    MAG("mag", "Magahi"),
    MAH("mah", "Marshallese"),
    MAI("mai", "Maithili"),
    MAK("mak", "Makasar"),
    MAL("mal", "Malayalam"),
    MAN("man", "Mandingo"),
    MAP("map", "Austronesian languages"),
    MAR("mar", "Marathi"),
    MAS("mas", "Masai"),
    MDF("mdf", "Moksha"),
    MDR("mdr", "Mandar"),
    MEN("men", "Mende"),
    MGA("mga", "Irish, Middle (900–1200)"),
    MIC("mic", "Mi'kmaq; Micmac"),
    MIN("min", "Minangkabau"),
    MIS("mis", "Uncoded languages"),
    MKD("mkd", "Macedonian"),
    MAC("mac", "Macedonian"),
    MKH("mkh", "Mon-Khmer languages"),
    MLG("mlg", "Malagasy"),
    MLT("mlt", "Maltese"),
    MNC("mnc", "Manchu"),
    MNI("mni", "Manipuri"),
    MNO("mno", "Manobo languages"),
    MOH("moh", "Mohawk"),
    MON("mon", "Mongolian"),
    MOS("mos", "Mossi"),
    MRI("mri", "Māori"),
    MAO("mao", "Māori"),
    MSA("msa", "Malay"),
    MAY("may", "Malay"),
    MUL("mul", "Multiple languages"),
    MUN("mun", "Munda languages"),
    MUS("mus", "Creek"),
    MWL("mwl", "Mirandese"),
    MWR("mwr", "Marwari"),
    MYA("mya", "Burmese"),
    BUR("bur", "Burmese"),
    MYN("myn", "Mayan languages"),
    MYV("myv", "Erzya"),
    NAH("nah", "Nahuatl languages"),
    NAI("nai", "North American Indian languages"),
    NAP("nap", "Neapolitan"),
    NAU("nau", "Nauru"),
    NAV("nav", "Navajo; Navaho"),
    NBL("nbl", "Ndebele, South; South Ndebele"),
    NDE("nde", "Ndebele, North; North Ndebele"),
    NDO("ndo", "Ndonga"),
    NDS("nds", "Low German; Low Saxon; German, Low; Saxon, Low"),
    NEP("nep", "Nepali"),
    NEW("new", "Nepal Bhasa; Newari"),
    NIA("nia", "Nias"),
    NIC("nic", "Niger-Kordofanian languages"),
    NIU("niu", "Niuean"),
    NLD("nld", "Dutch; Flemish"),
    DUT("dut", "Dutch; Flemish"),
    NNO("nno", "Norwegian Nynorsk; Nynorsk, Norwegian"),
    NOB("nob", "Bokmål, Norwegian; Norwegian Bokmål"),
    NOG("nog", "Nogai"),
    NON("non", "Norse, Old"),
    NOR("nor", "Norwegian"),
    NQO("nqo", "N'Ko"),
    NSO("nso", "Pedi; Sepedi; Northern Sotho"),
    NUB("nub", "Nubian languages"),
    NWC("nwc", "Classical Newari; Old Newari; Classical Nepal Bhasa"),
    NYA("nya", "Chichewa; Chewa; Nyanja"),
    NYM("nym", "Nyamwezi"),
    NYN("nyn", "Nyankole"),
    NYO("nyo", "Nyoro"),
    NZI("nzi", "Nzima"),
    OCI("oci", "Occitan (post 1500)"),
    OJI("oji", "Ojibwa"),
    ORI("ori", "Oriya"),
    ORM("orm", "Oromo"),
    OSA("osa", "Osage"),
    OSS("oss", "Ossetian; Ossetic"),
    OTA("ota", "Turkish, Ottoman (1500–1928)"),
    OTO("oto", "Otomian languages"),
    PAA("paa", "Papuan languages"),
    PAG("pag", "Pangasinan"),
    PAL("pal", "Pahlavi"),
    PAM("pam", "Pampanga; Kapampangan"),
    PAN("pan", "Panjabi; Punjabi"),
    PAP("pap", "Papiamento"),
    PAU("pau", "Palauan"),
    PEO("peo", "Persian, Old (c. 600–400 B.C.)"),
    PHI("phi", "Philippine languages"),
    PHN("phn", "Phoenician"),
    PLI("pli", "Pali"),
    POL("pol", "Polish"),
    PON("pon", "Pohnpeian"),
    POR("por", "Portuguese"),
    PRA("pra", "Prakrit languages"),
    PRO("pro", "Provençal, Old (to 1500); Old Occitan (to 1500)"),
    PUS("pus", "Pushto; Pashto"),
    QUE("que", "Quechua"),
    RAJ("raj", "Rajasthani"),
    RAP("rap", "Rapanui"),
    RAR("rar", "Rarotongan; Cook Islands Māori"),
    ROA("roa", "Romance languages"),
    ROH("roh", "Romansh"),
    ROM("rom", "Romany"),
    RON("ron", "Romanian; Moldavian; Moldovan"),
    RUM("rum", "Romanian; Moldavian; Moldovan"),
    RUN("run", "Rundi"),
    RUP("rup", "Aromanian; Arumanian; Macedo-Romanian[b]"),
    RUS("rus", "Russian"),
    SAD("sad", "Sandawe"),
    SAG("sag", "Sango"),
    SAH("sah", "Yakut"),
    SAI("sai", "South American Indian languages"),
    SAL("sal", "Salishan languages"),
    SAM("sam", "Samaritan Aramaic"),
    SAN("san", "Sanskrit"),
    SAS("sas", "Sasak"),
    SAT("sat", "Santali"),
    SCN("scn", "Sicilian"),
    SCO("sco", "Scots"),
    SEL("sel", "Selkup"),
    SEM("sem", "Semitic languages"),
    SGA("sga", "Irish, Old (to 900)"),
    SGN("sgn", "Sign Languages"),
    SHN("shn", "Shan"),
    SID("sid", "Sidamo"),
    SIN("sin", "Sinhala; Sinhalese"),
    SIO("sio", "Siouan languages"),
    SIT("sit", "Sino-Tibetan languages"),
    SLA("sla", "Slavic languages"),
    SLK("slk", "Slovak"),
    SLO("slo", "Slovak"),
    SLV("slv", "Slovenian"),
    SMA("sma", "Southern Sami"),
    SME("sme", "Northern Sami"),
    SMI("smi", "Sami languages"),
    SMJ("smj", "Lule Sami"),
    SMN("smn", "Inari Sami"),
    SMO("smo", "Samoan"),
    SMS("sms", "Skolt Sami"),
    SNA("sna", "Shona"),
    SND("snd", "Sindhi"),
    SNK("snk", "Soninke"),
    SOG("sog", "Sogdian"),
    SOM("som", "Somali"),
    SON("son", "Songhai languages"),
    SOT("sot", "Sotho, Southern"),
    SPA("spa", "Spanish; Castilian"),
    SQI("sqi", "Albanian"),
    ALB("alb", "Albanian"),
    SRD("srd", "Sardinian"),
    SRN("srn", "Sranan Tongo"),
    SRP("srp", "Serbian"),
    SRR("srr", "Serer"),
    SSA("ssa", "Nilo-Saharan languages"),
    SSW("ssw", "Swati"),
    SUK("suk", "Sukuma"),
    SUN("sun", "Sundanese"),
    SUS("sus", "Susu"),
    SUX("sux", "Sumerian"),
    SWA("swa", "Swahili"),
    SWE("swe", "Swedish"),
    SYC("syc", "Classical Syriac"),
    SYR("syr", "Syriac"),
    TAH("tah", "Tahitian"),
    TAI("tai", "Tai languages"),
    TAM("tam", "Tamil"),
    TAT("tat", "Tatar"),
    TEL("tel", "Telugu"),
    TEM("tem", "Timne"),
    TER("ter", "Tereno"),
    TET("tet", "Tetum"),
    TGK("tgk", "Tajik"),
    TGL("tgl", "Tagalog"),
    THA("tha", "Thai"),
    TIG("tig", "Tigre"),
    TIR("tir", "Tigrinya"),
    TIV("tiv", "Tiv"),
    TKL("tkl", "Tokelau"),
    TLH("tlh", "Klingon; tlhIngan-Hol"),
    TLI("tli", "Tlingit"),
    TMH("tmh", "Tamashek"),
    TOG("tog", "Tonga (Nyasa)"),
    TON("ton", "Tonga (Tonga Islands)"),
    TPI("tpi", "Tok Pisin"),
    TSI("tsi", "Tsimshian"),
    TSN("tsn", "Tswana"),
    TSO("tso", "Tsonga"),
    TUK("tuk", "Turkmen"),
    TUM("tum", "Tumbuka"),
    TUP("tup", "Tupi languages"),
    TUR("tur", "Turkish"),
    TUT("tut", "Altaic languages"),
    TVL("tvl", "Tuvalu"),
    TWI("twi", "Twi"),
    TYV("tyv", "Tuvinian"),
    UDM("udm", "Udmurt"),
    UGA("uga", "Ugaritic"),
    UIG("uig", "Uighur; Uyghur"),
    UKR("ukr", "Ukrainian"),
    UMB("umb", "Umbundu"),
    UND("und", "Undetermined"),
    URD("urd", "Urdu"),
    UZB("uzb", "Uzbek"),
    VAI("vai", "Vai"),
    VEN("ven", "Venda"),
    VIE("vie", "Vietnamese"),
    VOL("vol", "Volapük"),
    VOT("vot", "Votic"),
    WAK("wak", "Wakashan languages"),
    WAL("wal", "Wolaitta; Wolaytta"),
    WAR("war", "Waray"),
    WAS("was", "Washo"),
    WEN("wen", "Sorbian languages"),
    WLN("wln", "Walloon"),
    WOL("wol", "Wolof"),
    XAL("xal", "Kalmyk; Oirat"),
    XHO("xho", "Xhosa"),
    YAO("yao", "Yao"),
    YAP("yap", "Yapese"),
    YID("yid", "Yiddish"),
    YOR("yor", "Yoruba"),
    YPK("ypk", "Yupik languages"),
    ZAP("zap", "Zapotec"),
    ZBL("zbl", "Blissymbols; Blissymbolics; Bliss"),
    ZEN("zen", "Zenaga"),
    ZGH("zgh", "Standard Moroccan Tamazight"),
    ZHA("zha", "Zhuang; Chuang"),
    ZHO("zho", "Chinese"),
    CHI("chi", "Chinese"),
    ZND("znd", "Zande languages"),
    ZUL("zul", "Zulu"),
    ZUN("zun", "Zuni"),
    ZXX("zxx", "No linguistic content; Not applicable"),
    ZZA("zza", "Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki"),
}