package br.com.rodrigogurgel.streamingservice.domain

enum class UploadProcessStatusEnum(val value: String) {
    UPLOAD_PENDING("UPLOAD_PENDING"),
    UPLOAD_STARTED("UPLOAD_STARTED"),
    UPLOAD_COMPLETED("UPLOAD_COMPLETED"),
    UPLOAD_FAILED("UPLOAD_FAILED"),
    CONVERSION_PENDING("CONVERSION_PENDING"),
    CONVERSION_NOTIFICATION_FAILED("CONVERSION_NOTIFICATION_FAILED"),
    CONVERSION_STARTED("CONVERSION_STARTED"),
    CONVERSION_COMPLETED("CONVERSION_COMPLETED"),
    CONVERSION_FAILED("CONVERSION_FAILED"),
}